name: CI - master

on:
  pull_request: 
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none
      - name: Cache node_modules
        uses: actions/cache@v4
        id: tests
        env:
          cache-name: tests
        with:
          path: ./node_modules/
          key: tests-${{ hashFiles('./package-lock.json') }}
          restore-keys: tests-${{ hashFiles('./package-lock.json') }}
        timeout-minutes: 4
      - name: Install dependencies
        if: steps.tests.outputs.cache-hit != true
        run: npm ci
      - name: Run tests
        run: npm test
